// SPDX-FileCopyrightText: 2024 Shun Sakai
//
// SPDX-License-Identifier: CC0-1.0

= Creative Commons AsciiDoc
:creativecommons-url: https://creativecommons.org
:asciidoc-url: https://asciidoc.org/
:commonmark-url: https://commonmark.org/
:cc-licenses-url: {creativecommons-url}/licenses
:cc0-url: {creativecommons-url}/publicdomain/zero/1.0
:release-page-url: https://github.com/sorairolake/creative-commons-asciidoc/releases
:asciidoc-docs-url: https://docs.asciidoctor.org/asciidoc/latest/
:asciidoctor-url: https://asciidoctor.org/
:asciidoc-py-url: https://asciidoc-py.github.io/
:pandoc-url: https://pandoc.org/
:reuse-spec-url: https://reuse.software/spec/

This project provides {creativecommons-url}[Creative Commons] licenses in
{asciidoc-url}[AsciiDoc].

By default, these licenses are available as HTML or plain text. This project
aims to provide these licenses written in a markup language which has both the
document structure and human-readability. I think {commonmark-url}[Markdown] is
more popular than AsciiDoc as a lightweight markup language, but I chose
AsciiDoc because these licenses written in Markdown already exist, it can get
closer to the HTML's document structure than Markdown, and I personally prefer
Markdown to AsciiDoc.

This project is inspired by
https://github.com/idleberg/Creative-Commons-Markdown.

== Available licenses

This project provides version 4.0 of the Creative Commons license suite and CC0
in English. For details about Creative Commons licenses, see
https://creativecommons.org/share-your-work/cclicenses/.

CC BY 4.0::

  * link:assets/CC-BY-4.0.adoc[]
  * {cc-licenses-url}/by/4.0/deed.en[Deed]
  * {cc-licenses-url}/by/4.0/legalcode.en[Legal code]

CC BY-SA 4.0::

  * link:assets/CC-BY-SA-4.0.adoc[]
  * {cc-licenses-url}/by-sa/4.0/deed.en[Deed]
  * {cc-licenses-url}/by-sa/4.0/legalcode.en[Legal code]

CC BY-NC 4.0::

  * link:assets/CC-BY-NC-4.0.adoc[]
  * {cc-licenses-url}/by-nc/4.0/deed.en[Deed]
  * {cc-licenses-url}/by-nc/4.0/legalcode.en[Legal code]

CC BY-NC-SA 4.0::

  * link:assets/CC-BY-NC-SA-4.0.adoc[]
  * {cc-licenses-url}/by-nc-sa/4.0/deed.en[Deed]
  * {cc-licenses-url}/by-nc-sa/4.0/legalcode.en[Legal code]

CC BY-ND 4.0::

  * link:assets/CC-BY-ND-4.0.adoc[]
  * {cc-licenses-url}/by-nd/4.0/deed.en[Deed]
  * {cc-licenses-url}/by-nd/4.0/legalcode.en[Legal code]

CC BY-NC-ND 4.0::

  * link:assets/CC-BY-NC-ND-4.0.adoc[]
  * {cc-licenses-url}/by-nc-nd/4.0/deed.en[Deed]
  * {cc-licenses-url}/by-nc-nd/4.0/legalcode.en[Legal code]

CC0 1.0::

  * link:assets/CC0-1.0.adoc[]
  * {cc0-url}/deed.en[Deed]
  * {cc0-url}/legalcode.en[Legal code]

NOTE: The licenses in PDF are available on the {release-page-url}[release page].

The AsciiDoc-formatted Creative Commons licenses are dedicated to the public
domain under the {cc0-url}[CC0 Public Domain Dedication] as well as the text of
the Creative Commons public licenses.

== How to convert

The licenses are compliant with the
{asciidoc-docs-url}[AsciiDoc Language Documentation]. These can be converted to
other formats using {asciidoctor-url}[Asciidoctor].

TIP: The licenses can also be handled by {asciidoc-py-url}[AsciiDoc.py], but it
is recommended to use Asciidoctor to properly handle them.

.Convert AsciiDoc to HTML
[source,sh]
----
asciidoctor assets/CC-BY-4.0.adoc
----

.Convert AsciiDoc to PDF
[source,sh]
----
asciidoctor-pdf assets/CC0-1.0.adoc
----

For details about the available converters, see
https://docs.asciidoctor.org/asciidoctor/latest/convert/available/.

If you want to convert to a file format which does not have a converter, you
may be able to use {pandoc-url}[Pandoc].

.Convert AsciiDoc to GitHub Flavored Markdown
[source,sh]
----
asciidoctor -b docbook5 -o - -a leveloffset=+1 assets/CC-BY-SA-4.0.adoc \
    | pandoc -f docbook -t gfm \
    > CC-BY-SA-4.0.md
----

IMPORTANT: It may be desirable to tidy up the output file of Pandoc.

== Source code

The upstream repository is available at
https://github.com/sorairolake/creative-commons-asciidoc.git.

== Changelog

Please see link:CHANGELOG.adoc[].

== Contributing

Please see link:CONTRIBUTING.adoc[].

== Home page

https://sorairolake.github.io/creative-commons-asciidoc/

== License

* Copyright (C) 2009 Creative Commons
* Copyright (C) 2024 Shun Sakai

Unless otherwise noted, the contents of this repository are distributed under
the terms of the _CC0 1.0 Universal_.

This project is compliant with version 3.2 of the
{reuse-spec-url}[_REUSE Specification_]. See copyright notices of individual
files for more details on copyright and licensing information.
