# SPDX-FileCopyrightText: 2024 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

name: CD

on:
  push:
    tags:
      - "v[0-9][0-9][0-9][0-9].[0-1][0-9].[0-3][0-9]-?*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate PDF files
        uses: docker://asciidoctor/docker-asciidoctor:latest
        with:
          args: asciidoctor-pdf -a compress -D . assets/CC*.adoc
      - name: Calculate checksums
        run: |
          sha256sum CC*.pdf | tee sha256sums.txt
          b2sum CC*.pdf | tee b2sums.txt
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            CC*.pdf
            sha256sums.txt
            b2sums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
